/**
 * Built-in metric seed — data, not code (design doc §3.1, §4).
 *
 * Each metric has a stable `key` from which the fixed `MetricId`
 * (`builtin:<key>`) is derived. Units are UCUM codes that MUST exist in
 * `units-data.ts`. `molarMass` enables the mass-concentration <->
 * molar-concentration bridge (§2.2). Metric-specific `conversions` carry
 * affine relations that must override any derived conversion: HbA1c (% NGSP vs
 * mmol/mol IFCC share the `fraction` dimension but are not linearly related)
 * and triglycerides (conventional triolein factor, §4/§5.5).
 *
 * `typicalRange` is a WIDE sanity bound in the canonical unit for typo
 * detection only — never a medical reference range (§2.4). Reference ranges
 * belong to individual measurements.
 *
 * LOINC codes are the public seed (Regenstrief license permits embedding a
 * subset; see LOINC_ATTRIBUTION). No other external code system is shipped in
 * the built-in catalog (no open license, §5.2); any additional codes
 * (`externalCodes.other`) are user-local only.
 */

import type { Metric, MetricId } from './types';

/**
 * Mandatory attribution for the embedded LOINC subset (design doc §5.1).
 * Surface this in the app's About/License screen and repository LICENSE.
 */
export const LOINC_ATTRIBUTION: string =
  'This material contains content from LOINC (http://loinc.org). LOINC is ' +
  'copyright © Regenstrief Institute, Inc. and the LOINC Committee and is ' +
  'available at no cost under the license at http://loinc.org/license. ' +
  'LOINC® is a registered United States trademark of Regenstrief Institute, Inc.';

/**
 * Seed entries without `id`; the `builtin:<key>` id is derived below so it can
 * never drift from the key.
 */
const SEED: readonly Omit<Metric, 'id'>[] = [
  // --- Lipids -------------------------------------------------------------
  {
    key: 'total-cholesterol',
    nameKey: 'metric.total-cholesterol',
    aliases: [
      'Cholesterol',
      'Total cholesterol',
      'Celkový cholesterol',
      'Cholesterol celkový',
      'S-Cholesterol',
      'Chol',
      'TC',
      'CHOL',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 386.65,
    externalCodes: { loinc: '2093-3' },
    precision: { 'mmol/L': 2, 'mg/dL': 0 },
    typicalRange: { low: 0.5, high: 30 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'ldl-cholesterol',
    nameKey: 'metric.ldl-cholesterol',
    aliases: [
      'LDL',
      'LDL-C',
      'LDL cholesterol',
      'LDL-cholesterol',
      'Cholesterol LDL',
      'S-LDL cholesterol',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 386.65,
    externalCodes: { loinc: '13457-7' },
    precision: { 'mmol/L': 2, 'mg/dL': 0 },
    typicalRange: { low: 0.2, high: 25 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'hdl-cholesterol',
    nameKey: 'metric.hdl-cholesterol',
    aliases: [
      'HDL',
      'HDL-C',
      'HDL cholesterol',
      'HDL-cholesterol',
      'Cholesterol HDL',
      'S-HDL cholesterol',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 386.65,
    externalCodes: { loinc: '2085-9' },
    precision: { 'mmol/L': 2, 'mg/dL': 0 },
    typicalRange: { low: 0.1, high: 10 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'triglycerides',
    nameKey: 'metric.triglycerides',
    aliases: [
      'Triglycerides',
      'Triglyceridy',
      'Triacylglyceroly',
      'S-Triacylglyceroly',
      'TAG',
      'TG',
      'TRIG',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    // Conventional triolein factor mmol/L -> mg/dL (§4, §5.5). Kept explicit
    // (not a single molar mass) so it overrides any derived conversion.
    conversions: [{ fromUnit: 'mmol/L', toUnit: 'mg/dL', factor: 88.57 }],
    externalCodes: { loinc: '2571-8' },
    precision: { 'mmol/L': 2, 'mg/dL': 0 },
    typicalRange: { low: 0.1, high: 50 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },

  // --- Glucose metabolism -------------------------------------------------
  {
    key: 'glucose',
    nameKey: 'metric.glucose',
    aliases: [
      'Glucose',
      'Glukóza',
      'Glukoza',
      'Glykémie',
      'S-Glukóza',
      'Krevní cukr',
      'GLU',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 180.16,
    externalCodes: { loinc: '2345-7' },
    precision: { 'mmol/L': 2, 'mg/dL': 0 },
    typicalRange: { low: 1, high: 50 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'hba1c',
    nameKey: 'metric.hba1c',
    aliases: ['HbA1c', 'Glykovaný hemoglobin', 'Glykohemoglobin', 'Hemoglobin A1c', 'A1c'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/mol',
    units: ['mmol/mol', '%'],
    // NGSP % = 0.09148 * IFCC(mmol/mol) + 2.152 (§2.2, §5).
    conversions: [{ fromUnit: 'mmol/mol', toUnit: '%', factor: 0.09148, offset: 2.152 }],
    externalCodes: { loinc: '4548-4' },
    precision: { 'mmol/mol': 0, '%': 1 },
    typicalRange: { low: 10, high: 200 },
    preferredUnitByLocale: { cs: 'mmol/mol', en: '%' },
  },

  // --- Renal --------------------------------------------------------------
  {
    key: 'creatinine',
    nameKey: 'metric.creatinine',
    aliases: ['Creatinine', 'Kreatinin', 'S-Kreatinin', 'Krea', 'CREA'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L', 'mg/dL'],
    molarMass: 113.12,
    externalCodes: { loinc: '2160-0' },
    precision: { 'umol/L': 0, 'mg/dL': 2 },
    typicalRange: { low: 10, high: 2000 },
    preferredUnitByLocale: { cs: 'umol/L', en: 'mg/dL' },
  },
  {
    key: 'egfr',
    nameKey: 'metric.egfr',
    aliases: [
      'eGFR',
      'GFR',
      'Glomerulární filtrace',
      'Odhadovaná glomerulární filtrace',
      'CKD-EPI',
      'MDRD',
      // SYNLAB / Czech phrasings of the CKD-EPI estimate. The trailing "(Krea)"
      // qualifier is stripped by resolveMetric, so the base phrase must resolve
      // to eGFR here — otherwise the parenthetical "Krea" would leak it onto
      // creatinine (a wrong-metric data-integrity bug).
      'Odhad filtr. CKD-EPI',
      'Odhad filtrace CKD-EPI',
      'Odhad glomerulární filtrace CKD-EPI',
      'Odhad GF CKD-EPI',
      'eGFR CKD-EPI',
      'Odhad filtr. MDRD',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mL/min/{1.73_m2}',
    units: ['mL/min/{1.73_m2}', 'mL/s/{1.73_m2}'],
    // Czech labs report in ml/s per 1.73 m²: 1 ml/s = 60 ml/min per 1.73 m².
    conversions: [{ fromUnit: 'mL/s/{1.73_m2}', toUnit: 'mL/min/{1.73_m2}', factor: 60 }],
    externalCodes: { loinc: '33914-3' },
    precision: { 'mL/min/{1.73_m2}': 0, 'mL/s/{1.73_m2}': 2 },
    typicalRange: { low: 1, high: 200 },
  },
  {
    key: 'uric-acid',
    nameKey: 'metric.uric-acid',
    aliases: ['Uric acid', 'Kyselina močová', 'Urát', 'Urate', 'S-Kyselina močová', 'KM'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L', 'mg/dL'],
    molarMass: 168.11,
    externalCodes: { loinc: '3084-1' },
    precision: { 'umol/L': 0, 'mg/dL': 1 },
    typicalRange: { low: 50, high: 2000 },
    preferredUnitByLocale: { cs: 'umol/L', en: 'mg/dL' },
  },

  // --- Liver --------------------------------------------------------------
  {
    key: 'alt',
    nameKey: 'metric.alt',
    aliases: ['ALT', 'ALAT', 'Alaninaminotransferáza', 'Alanine aminotransferase', 'S-ALT'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    externalCodes: { loinc: '1742-6' },
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0.05, high: 50 },
  },
  {
    key: 'ast',
    nameKey: 'metric.ast',
    aliases: ['AST', 'ASAT', 'Aspartátaminotransferáza', 'Aspartate aminotransferase', 'S-AST'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    externalCodes: { loinc: '1920-8' },
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0.05, high: 50 },
  },
  {
    key: 'ggt',
    nameKey: 'metric.ggt',
    aliases: ['GGT', 'GMT', 'Gama-glutamyltransferáza', 'Gamma-glutamyl transferase', 'S-GGT'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    externalCodes: { loinc: '2324-2' },
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0.05, high: 100 },
  },
  {
    key: 'alp',
    nameKey: 'metric.alp',
    aliases: ['ALP', 'Alkalická fosfatáza', 'Alkaline phosphatase', 'ALKP', 'S-ALP'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    externalCodes: { loinc: '6768-6' },
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0.1, high: 100 },
  },
  {
    key: 'bilirubin-total',
    nameKey: 'metric.bilirubin-total',
    aliases: [
      'Bilirubin',
      'Total bilirubin',
      'Bilirubin celkový',
      'Celkový bilirubin',
      'S-Bilirubin',
      'TBIL',
      'BILI',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L', 'mg/dL'],
    molarMass: 584.66,
    externalCodes: { loinc: '1975-2' },
    precision: { 'umol/L': 1, 'mg/dL': 2 },
    typicalRange: { low: 1, high: 600 },
    preferredUnitByLocale: { cs: 'umol/L', en: 'mg/dL' },
  },

  // --- Inflammation / endocrine ------------------------------------------
  {
    key: 'crp',
    nameKey: 'metric.crp',
    aliases: ['CRP', 'C-reaktivní protein', 'C-reactive protein', 'S-CRP'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mg/L',
    units: ['mg/L'],
    externalCodes: { loinc: '1988-5' },
    precision: { 'mg/L': 1 },
    typicalRange: { low: 0, high: 500 },
  },
  {
    key: 'tsh',
    nameKey: 'metric.tsh',
    aliases: ['TSH', 'Tyreotropin', 'Thyrotropin', 'Tyreostimulační hormon', 'S-TSH'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'm[IU]/L',
    units: ['m[IU]/L'],
    externalCodes: { loinc: '3016-3' },
    precision: { 'm[IU]/L': 2 },
    typicalRange: { low: 0.001, high: 100 },
  },
  {
    key: 'vitamin-d',
    nameKey: 'metric.vitamin-d',
    aliases: [
      'Vitamin D',
      'Vitamín D',
      '25-OH vitamin D',
      '25-hydroxyvitamin D',
      '25(OH)D',
      'Kalcidiol',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L', 'ng/mL'],
    molarMass: 400.64,
    externalCodes: { loinc: '62292-8' },
    precision: { 'nmol/L': 0, 'ng/mL': 1 },
    typicalRange: { low: 5, high: 500 },
    preferredUnitByLocale: { cs: 'nmol/L', en: 'ng/mL' },
  },
  {
    key: 'vitamin-b12',
    nameKey: 'metric.vitamin-b12',
    aliases: [
      'Vitamin B12',
      'Vitamín B12',
      'Vitamin B-12',
      'B12',
      'Kobalamin',
      'Cobalamin',
      'Cyanokobalamin',
      'S-Vitamin B12',
    ],
    category: 'lab',
    valueType: 'number',
    // Serum B12 is reported in pmol/l (SI, common in CZ) or ng/l ≡ pg/ml (US).
    canonicalUnit: 'pmol/L',
    units: ['pmol/L', 'ng/L'],
    molarMass: 1355.37,
    externalCodes: { loinc: '2132-9' },
    precision: { 'pmol/L': 0, 'ng/L': 0 },
    typicalRange: { low: 30, high: 2000 },
    preferredUnitByLocale: { cs: 'pmol/L', en: 'ng/L' },
  },
  {
    key: 'folate',
    nameKey: 'metric.folate',
    aliases: [
      'Kyselina listová',
      'Folát',
      'Folate',
      'Folic acid',
      'Vitamin B9',
      'S-Folát',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L', 'ug/L', 'ng/mL'],
    molarMass: 441.4,
    externalCodes: { loinc: '2284-8' },
    precision: { 'nmol/L': 1, 'ug/L': 1, 'ng/mL': 1 },
    typicalRange: { low: 1, high: 60 },
    preferredUnitByLocale: { cs: 'nmol/L', en: 'ng/mL' },
  },

  // --- Iron / tumour markers ---------------------------------------------
  {
    key: 'ferritin',
    nameKey: 'metric.ferritin',
    aliases: ['Ferritin', 'Feritin', 'S-Ferritin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L', 'ng/mL'],
    externalCodes: { loinc: '2276-4' },
    precision: { 'ug/L': 0, 'ng/mL': 0 },
    typicalRange: { low: 1, high: 5000 },
  },
  {
    key: 'iron',
    nameKey: 'metric.iron',
    aliases: ['Iron', 'Železo', 'Sérové železo', 'S-Železo', 'Fe'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L', 'ug/dL'],
    molarMass: 55.85,
    externalCodes: { loinc: '2498-4' },
    precision: { 'umol/L': 1, 'ug/dL': 0 },
    typicalRange: { low: 1, high: 100 },
    preferredUnitByLocale: { cs: 'umol/L', en: 'ug/dL' },
  },
  {
    key: 'psa',
    nameKey: 'metric.psa',
    aliases: [
      'PSA',
      'Prostatický specifický antigen',
      'Prostate specific antigen',
      'PSA celkové',
      'Total PSA',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L', 'ng/mL'],
    externalCodes: { loinc: '2857-1' },
    precision: { 'ug/L': 2, 'ng/mL': 2 },
    typicalRange: { low: 0, high: 200 },
  },

  // --- Haematology --------------------------------------------------------
  {
    key: 'hemoglobin',
    nameKey: 'metric.hemoglobin',
    aliases: ['Hemoglobin', 'Hgb', 'HGB', 'Hb', 'Krevní barvivo'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L', 'g/dL'],
    externalCodes: { loinc: '718-7' },
    precision: { 'g/L': 0, 'g/dL': 1 },
    typicalRange: { low: 30, high: 250 },
    preferredUnitByLocale: { cs: 'g/L', en: 'g/dL' },
  },
  {
    key: 'leukocytes',
    nameKey: 'metric.leukocytes',
    aliases: ['Leukocytes', 'Leukocyty', 'Bílé krvinky', 'White blood cells', 'WBC', 'Leu'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '10*9/L',
    units: ['10*9/L'],
    externalCodes: { loinc: '6690-2' },
    precision: { '10*9/L': 1 },
    typicalRange: { low: 0.5, high: 200 },
  },
  {
    key: 'thrombocytes',
    nameKey: 'metric.thrombocytes',
    aliases: ['Thrombocytes', 'Trombocyty', 'Krevní destičky', 'Destičky', 'Platelets', 'PLT'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '10*9/L',
    units: ['10*9/L'],
    externalCodes: { loinc: '777-3' },
    precision: { '10*9/L': 0 },
    typicalRange: { low: 5, high: 2000 },
  },

  // --- Vitals / home measurements ----------------------------------------
  {
    key: 'bp-systolic',
    nameKey: 'metric.bp-systolic',
    aliases: [
      'Systolic blood pressure',
      'Systolický tlak',
      'Tlak systolický',
      'Systola',
      'TK systola',
      'SBP',
      'SYS',
      // The group is entered as one unit; make it findable by its common names.
      'Krevní tlak',
      'Blood pressure',
      'Tlak',
    ],
    category: 'home',
    valueType: 'number',
    canonicalUnit: 'mm[Hg]',
    units: ['mm[Hg]', 'kPa'],
    externalCodes: { loinc: '8480-6' },
    precision: { 'mm[Hg]': 0, kPa: 1 },
    typicalRange: { low: 40, high: 300 },
    entryGroup: 'blood-pressure',
  },
  {
    key: 'bp-diastolic',
    nameKey: 'metric.bp-diastolic',
    aliases: [
      'Diastolic blood pressure',
      'Diastolický tlak',
      'Tlak diastolický',
      'Diastola',
      'TK diastola',
      'DBP',
      'DIA',
    ],
    category: 'home',
    valueType: 'number',
    canonicalUnit: 'mm[Hg]',
    units: ['mm[Hg]', 'kPa'],
    externalCodes: { loinc: '8462-4' },
    precision: { 'mm[Hg]': 0, kPa: 1 },
    typicalRange: { low: 20, high: 200 },
    entryGroup: 'blood-pressure',
  },
  {
    key: 'heart-rate',
    nameKey: 'metric.heart-rate',
    aliases: ['Heart rate', 'Tepová frekvence', 'Tep', 'Puls', 'Pulse', 'HR', 'TF'],
    category: 'home',
    valueType: 'number',
    canonicalUnit: '/min',
    units: ['/min'],
    externalCodes: { loinc: '8867-4' },
    precision: { '/min': 0 },
    typicalRange: { low: 20, high: 300 },
    entryGroup: 'blood-pressure',
  },
  {
    key: 'body-weight',
    nameKey: 'metric.body-weight',
    aliases: ['Body weight', 'Hmotnost', 'Váha', 'Tělesná hmotnost', 'Weight'],
    category: 'home',
    valueType: 'number',
    canonicalUnit: 'kg',
    units: ['kg', '[lb_av]'],
    externalCodes: { loinc: '29463-7' },
    precision: { kg: 1, '[lb_av]': 1 },
    typicalRange: { low: 20, high: 300 },
    preferredUnitByLocale: { cs: 'kg', en: '[lb_av]' },
  },
  {
    key: 'waist',
    nameKey: 'metric.waist',
    aliases: ['Waist circumference', 'Obvod pasu', 'Pas', 'Waist'],
    category: 'home',
    valueType: 'number',
    canonicalUnit: 'cm',
    units: ['cm', '[in_i]'],
    externalCodes: { loinc: '8280-0' },
    precision: { cm: 1, '[in_i]': 1 },
    typicalRange: { low: 30, high: 250 },
    preferredUnitByLocale: { cs: 'cm', en: '[in_i]' },
  },
  {
    key: 'body-temperature',
    nameKey: 'metric.body-temperature',
    aliases: ['Body temperature', 'Tělesná teplota', 'Teplota', 'Temperature', 'Horečka'],
    category: 'home',
    valueType: 'number',
    canonicalUnit: 'Cel',
    units: ['Cel', '[degF]'],
    externalCodes: { loinc: '8310-5' },
    precision: { Cel: 1, '[degF]': 1 },
    typicalRange: { low: 30, high: 45 },
    preferredUnitByLocale: { cs: 'Cel', en: '[degF]' },
  },
  {
    key: 'spo2',
    nameKey: 'metric.spo2',
    aliases: [
      'SpO2',
      'Saturace kyslíku',
      'Saturace',
      'Kyslíková saturace',
      'Oxygen saturation',
      'O2 saturation',
    ],
    category: 'home',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    externalCodes: { loinc: '59408-5' },
    precision: { '%': 0 },
    typicalRange: { low: 50, high: 100 },
  },

  // --- ÚZIS national-catalog extension (state-ready lab analytes) ---------

  // --- Lipids / cardiac ---------------------------------------------------
  {
    key: 'lipoprotein-a',
    nameKey: 'metric.lipoprotein-a',
    aliases: ['Lp(a)', 'Lipoprotein(a)', 'Lipoprotein (a)', 'Lipoprotein a', 'LPA'],
    category: 'lab',
    valueType: 'number',
    // Canonical nmol/L only. Lp(a) has no fixed particle mass, so nmol/L and
    // mg/dL are NOT linearly related (no molar bridge); mg/dL is intentionally
    // omitted rather than shipped with an invalid conversion.
    canonicalUnit: 'nmol/L',
    units: ['nmol/L'],
    externalCodes: { loinc: '43583-4' },
    precision: { 'nmol/L': 0 },
    typicalRange: { low: 0, high: 1000 },
  },
  {
    key: 'nt-probnp',
    nameKey: 'metric.nt-probnp',
    aliases: [
      'NT-proBNP',
      'NTproBNP',
      'NT proBNP',
      'N-terminal pro-BNP',
      'N-terminální pro-BNP',
      'proBNP',
    ],
    category: 'lab',
    valueType: 'number',
    // ng/L and pg/mL are numerically identical (same dimension, equal factor).
    canonicalUnit: 'ng/L',
    units: ['ng/L', 'pg/mL'],
    externalCodes: { loinc: '33762-6' },
    precision: { 'ng/L': 0, 'pg/mL': 0 },
    typicalRange: { low: 0, high: 100000 },
  },

  // --- Renal / metabolic --------------------------------------------------
  {
    key: 'urea',
    nameKey: 'metric.urea',
    aliases: ['Urea', 'Močovina', 'S-Urea', 'S-Močovina', 'Urea v séru'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 60.06,
    externalCodes: { loinc: '22664-7' },
    precision: { 'mmol/L': 1, 'mg/dL': 0 },
    typicalRange: { low: 0.1, high: 100 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },

  // --- Endocrine ----------------------------------------------------------
  {
    key: 'ft4',
    nameKey: 'metric.ft4',
    aliases: [
      'fT4',
      'FT4',
      'Free T4',
      'Free thyroxine',
      'Volný tyroxin',
      'Tyroxin volný',
      'T4 volný',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'pmol/L',
    units: ['pmol/L', 'ng/dL'],
    // Thyroxine (T4), C15H11I4NO4 = 776.87 g/mol — bridges pmol/L <-> ng/dL.
    molarMass: 776.87,
    externalCodes: { loinc: '3024-7' },
    precision: { 'pmol/L': 1, 'ng/dL': 2 },
    typicalRange: { low: 1, high: 150 },
    preferredUnitByLocale: { cs: 'pmol/L', en: 'ng/dL' },
  },
  {
    key: 'c-peptide',
    nameKey: 'metric.c-peptide',
    aliases: ['C-peptid', 'C-peptide', 'C peptid', 'C-Peptide'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L', 'ug/L'],
    // Human C-peptide, 3020.29 g/mol — bridges nmol/L <-> µg/L.
    molarMass: 3020.29,
    externalCodes: { loinc: '1986-9' },
    precision: { 'nmol/L': 2, 'ug/L': 2 },
    typicalRange: { low: 0, high: 50 },
  },
  {
    key: 'anti-gad',
    nameKey: 'metric.anti-gad',
    aliases: [
      'Anti-GAD',
      'Anti-GAD65',
      'GAD protilátky',
      'GAD65',
      'GAD65 protilátky',
      'GAD antibodies',
    ],
    category: 'lab',
    valueType: 'number',
    // Assay-defined arbitrary units; no cross-unit conversion.
    canonicalUnit: 'U/mL',
    units: ['U/mL'],
    externalCodes: { loinc: '13926-1' },
    precision: { 'U/mL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },

  // --- Urine analytes -----------------------------------------------------
  {
    key: 'urine-protein',
    nameKey: 'metric.urine-protein',
    aliases: [
      'U-protein',
      'Bílkovina v moči',
      'Urine protein',
      'Protein v moči',
      'Celková bílkovina v moči',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L', 'mg/L'],
    externalCodes: { loinc: '2888-6' },
    precision: { 'g/L': 2, 'mg/L': 0 },
    typicalRange: { low: 0, high: 50 },
  },
  {
    key: 'urine-glucose',
    nameKey: 'metric.urine-glucose',
    aliases: [
      'Glukóza v moči',
      'Glucose, urine',
      'Glukóza moč',
      'U-Glukóza',
      'Glucose urine',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '25428-4' },
  },
  {
    key: 'urine-ketones',
    nameKey: 'metric.urine-ketones',
    aliases: [
      'Ketolátky v moči',
      'Ketones, urine',
      'Ketolátky moč',
      'Ketony v moči',
      'Ketones urine',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '2514-8' },
  },
  {
    key: 'urine-bilirubin',
    nameKey: 'metric.urine-bilirubin',
    aliases: [
      'Bilirubin v moči',
      'Bilirubin, urine',
      'Bilirubin moč',
      'Bilirubin urine',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '5770-3' },
  },
  {
    key: 'urine-urobilinogen',
    nameKey: 'metric.urine-urobilinogen',
    aliases: [
      'Urobilinogen v moči',
      'Urobilinogen, urine',
      'Urobilinogen moč',
      'Urobilinogen urine',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '5818-0' },
  },
  {
    key: 'urine-nitrite',
    nameKey: 'metric.urine-nitrite',
    aliases: [
      'Nitrity v moči',
      'Nitrite, urine',
      'Nitrity moč',
      'Nitrit v moči',
      'Nitrite urine',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '5802-4' },
  },
  {
    key: 'urine-blood',
    nameKey: 'metric.urine-blood',
    aliases: [
      'Krev v moči',
      'Blood, urine',
      'Krev moč',
      'Hemoglobin v moči',
      'Blood urine',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '5794-3' },
  },
  {
    key: 'urine-leukocyte-esterase',
    nameKey: 'metric.urine-leukocyte-esterase',
    aliases: [
      'Leukocyty v moči',
      'Leukocytes, urine',
      'Leukocyty moč',
      'Leukocytová esteráza',
      'Leukocyte esterase',
    ],
    category: 'lab',
    valueType: 'text',
    canonicalUnit: '',
    units: [],
    externalCodes: { loinc: '5799-2' },
  },
  {
    key: 'urine-ph',
    nameKey: 'metric.urine-ph',
    aliases: ['pH moči', 'Urine pH', 'pH v moči', 'pH moč'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[pH]',
    units: ['[pH]'],
    externalCodes: { loinc: '5803-2' },
    precision: { '[pH]': 1 },
    typicalRange: { low: 4, high: 9 },
  },
  {
    key: 'urine-albumin',
    nameKey: 'metric.urine-albumin',
    aliases: [
      'Mikroalbuminurie',
      'Albumin v moči',
      'Mikroalbumin',
      'Microalbumin',
      'Urine albumin',
      'U-albumin',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mg/L',
    units: ['mg/L'],
    externalCodes: { loinc: '14957-5' },
    precision: { 'mg/L': 1 },
    typicalRange: { low: 0, high: 5000 },
  },
  {
    key: 'urine-creatinine',
    nameKey: 'metric.urine-creatinine',
    aliases: ['Kreatinin v moči', 'U-kreatinin', 'Urine creatinine', 'Creatinine urine'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 113.12,
    externalCodes: { loinc: '2161-8' },
    precision: { 'mmol/L': 1, 'mg/dL': 0 },
    typicalRange: { low: 0.1, high: 100 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'acr',
    nameKey: 'metric.acr',
    aliases: [
      'ACR',
      'UACR',
      'Poměr albumin/kreatinin',
      'Albumin/creatinine ratio',
      'Albumin-creatinine ratio',
    ],
    category: 'lab',
    valueType: 'number',
    // A ratio; no unit conversion in the MVP.
    canonicalUnit: 'mg/mmol',
    units: ['mg/mmol'],
    externalCodes: { loinc: '14959-1' },
    precision: { 'mg/mmol': 1 },
    typicalRange: { low: 0, high: 3000 },
  },

  // --- Oncology / screening ----------------------------------------------
  {
    key: 'fob',
    nameKey: 'metric.fob',
    aliases: [
      'FOB',
      'FOBT',
      'FIT',
      'Okultní krvácení ve stolici',
      'Okultní krvácení',
      'Fecal occult blood',
      'Hemoglobin ve stolici',
    ],
    category: 'lab',
    valueType: 'number',
    // Quantitative FIT: µg haemoglobin per g of feces (arbitrary mass/mass).
    canonicalUnit: 'ug/g',
    units: ['ug/g'],
    externalCodes: { loinc: '27396-1' },
    precision: { 'ug/g': 1 },
    typicalRange: { low: 0, high: 10000 },
  },
  {
    key: 'psa-free',
    nameKey: 'metric.psa-free',
    aliases: [
      'PSA volný',
      'Volné PSA',
      'Free PSA',
      'fPSA',
      'PSA free',
      'Free prostate specific antigen',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L', 'ng/mL'],
    externalCodes: { loinc: '10886-0' },
    precision: { 'ug/L': 2, 'ng/mL': 2 },
    typicalRange: { low: 0, high: 200 },
  },
  {
    key: 'p2psa',
    nameKey: 'metric.p2psa',
    aliases: ['p2PSA', 'proPSA', '[-2]proPSA', 'ProPSA', '-2proPSA'],
    category: 'lab',
    valueType: 'number',
    // ng/L and pg/mL are numerically identical.
    canonicalUnit: 'ng/L',
    units: ['ng/L', 'pg/mL'],
    externalCodes: { loinc: '97149-9' },
    precision: { 'ng/L': 0, 'pg/mL': 0 },
    typicalRange: { low: 0, high: 100000 },
  },

  // --- Common lab panel (haematology / electrolytes / metabolic) ---------
  {
    key: 'erythrocytes',
    nameKey: 'metric.erythrocytes',
    aliases: ['Erythrocytes', 'Erytrocyty', 'Červené krvinky', 'Red blood cells', 'RBC', 'Ery'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '10*12/L',
    units: ['10*12/L'],
    externalCodes: { loinc: '789-8' },
    precision: { '10*12/L': 2 },
    typicalRange: { low: 1, high: 10 },
  },
  {
    key: 'hematocrit',
    nameKey: 'metric.hematocrit',
    aliases: ['Hematocrit', 'Hematokrit', 'HCT', 'Ht'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'L/L',
    units: ['L/L', '%'],
    externalCodes: { loinc: '4544-3' },
    precision: { 'L/L': 3, '%': 1 },
    typicalRange: { low: 0.1, high: 0.8 },
  },
  {
    key: 'mcv',
    nameKey: 'metric.mcv',
    aliases: [
      'Mean corpuscular volume',
      'Střední objem erytrocytu',
      'MCV',
      'Stř. objem ery.',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'fL',
    units: ['fL'],
    externalCodes: { loinc: '787-2' },
    precision: { fL: 1 },
    typicalRange: { low: 40, high: 150 },
  },
  {
    key: 'mch',
    nameKey: 'metric.mch',
    aliases: [
      'Mean corpuscular hemoglobin',
      'Střední barvivo erytrocytu',
      'MCH',
      'Barvivo ery.',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'pg',
    units: ['pg'],
    externalCodes: { loinc: '785-6' },
    precision: { pg: 1 },
    typicalRange: { low: 10, high: 50 },
  },
  {
    key: 'mchc',
    nameKey: 'metric.mchc',
    aliases: [
      'Mean corpuscular hemoglobin concentration',
      'Střední koncentrace hemoglobinu',
      'MCHC',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L', 'g/dL'],
    externalCodes: { loinc: '786-4' },
    precision: { 'g/L': 0, 'g/dL': 1 },
    typicalRange: { low: 200, high: 400 },
  },
  {
    key: 'rdw',
    nameKey: 'metric.rdw',
    aliases: ['Red cell distribution width', 'Distribuční šíře erytrocytů', 'RDW', 'RDW-CV', 'RDW-SD'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    externalCodes: { loinc: '788-0' },
    precision: { '%': 1 },
    typicalRange: { low: 5, high: 40 },
  },
  {
    key: 'mpv',
    nameKey: 'metric.mpv',
    aliases: ['Mean platelet volume', 'Střední objem trombocytu', 'MPV'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'fL',
    units: ['fL'],
    externalCodes: { loinc: '32623-1' },
    precision: { fL: 1 },
    typicalRange: { low: 3, high: 25 },
  },
  {
    key: 'sodium',
    nameKey: 'metric.sodium',
    aliases: ['Sodium', 'Sodík', 'Natrium', 'Na'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L'],
    externalCodes: { loinc: '2951-2' },
    precision: { 'mmol/L': 0 },
    typicalRange: { low: 80, high: 200 },
  },
  {
    key: 'potassium',
    nameKey: 'metric.potassium',
    aliases: ['Potassium', 'Draslík', 'Kalium', 'K'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L'],
    externalCodes: { loinc: '2823-3' },
    precision: { 'mmol/L': 1 },
    typicalRange: { low: 1, high: 10 },
  },
  {
    key: 'chloride',
    nameKey: 'metric.chloride',
    aliases: ['Chloride', 'Chloridy', 'Chlor', 'Cl'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L'],
    externalCodes: { loinc: '2075-0' },
    precision: { 'mmol/L': 0 },
    typicalRange: { low: 60, high: 140 },
  },
  {
    key: 'calcium',
    nameKey: 'metric.calcium',
    aliases: ['Calcium', 'Vápník', 'Kalcium', 'Ca'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L'],
    externalCodes: { loinc: '2000-8' },
    precision: { 'mmol/L': 2 },
    typicalRange: { low: 1, high: 5 },
  },
  {
    key: 'magnesium',
    nameKey: 'metric.magnesium',
    aliases: ['Magnesium', 'Hořčík', 'Magnézium', 'Mg'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L'],
    externalCodes: { loinc: '19123-9' },
    precision: { 'mmol/L': 2 },
    typicalRange: { low: 0.1, high: 3 },
  },
  {
    key: 'albumin',
    nameKey: 'metric.albumin',
    aliases: ['Albumin', 'ALB', 'S-Albumin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L'],
    externalCodes: { loinc: '1751-7' },
    precision: { 'g/L': 0 },
    typicalRange: { low: 10, high: 70 },
  },
  {
    key: 'total-protein',
    nameKey: 'metric.total-protein',
    aliases: [
      'Total protein',
      'Celková bílkovina',
      'Celkový protein',
      'CB',
      'TP',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L'],
    externalCodes: { loinc: '2885-2' },
    precision: { 'g/L': 0 },
    typicalRange: { low: 20, high: 130 },
  },
  {
    key: 'lipase',
    nameKey: 'metric.lipase',
    aliases: ['Lipase', 'Lipáza', 'LIP'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    externalCodes: { loinc: '3040-3' },
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0, high: 30 },
  },

  // --- Seed expansion: routine cross-category analytes + SmartMedix gaps ---
  // No LOINC is shipped for these: the source corpus (Czech lab handbooks /
  // requisitions) carries no LOINC, and a code is added to the public seed only
  // when it is a well-established public code — never invented (see §0/§5.2 of
  // the seed analysis). Codes may be supplemented later (packs / user-local).

  // Lipids (SmartMedix gap + apolipoproteins)
  {
    key: 'non-hdl-cholesterol',
    nameKey: 'metric.non-hdl-cholesterol',
    aliases: [
      'non-HDL',
      'non-HDL cholesterol',
      'non-HDL-C',
      'nonHDL cholesterol',
      'Non-HDL cholesterol',
      'Cholesterol non-HDL',
      'Non-HDL',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    molarMass: 386.65,
    precision: { 'mmol/L': 2, 'mg/dL': 0 },
    typicalRange: { low: 0.2, high: 25 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'apolipoprotein-a1',
    nameKey: 'metric.apolipoprotein-a1',
    aliases: ['Apolipoprotein A1', 'Apo A1', 'ApoA1', 'Apo A-I', 'Apolipoprotein A-I', 'ApoA-I'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L'],
    precision: { 'g/L': 2 },
    typicalRange: { low: 0.1, high: 5 },
  },
  {
    key: 'apolipoprotein-b',
    nameKey: 'metric.apolipoprotein-b',
    aliases: ['Apolipoprotein B', 'Apo B', 'ApoB', 'Apo B-100', 'Apolipoprotein B-100'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L'],
    precision: { 'g/L': 2 },
    typicalRange: { low: 0.1, high: 5 },
  },

  // Enzymes (serum)
  {
    key: 'amylase',
    nameKey: 'metric.amylase',
    aliases: ['Amylase', 'Amyláza', 'Amyláza v séru', 'S-Amyláza', 'AMS', 'α-amyláza', 'Alfa-amyláza'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'amylase-pancreatic',
    nameKey: 'metric.amylase-pancreatic',
    aliases: [
      'Pancreatic amylase',
      'Amyláza pankreatická',
      'Pankreatická amyláza',
      'AMS pankreat.',
      'P-amyláza',
      'P-AMS',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'ld',
    nameKey: 'metric.ld',
    aliases: ['LD', 'LDH', 'Laktátdehydrogenáza', 'Lactate dehydrogenase', 'S-LD'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0, high: 500 },
  },
  {
    key: 'ck',
    nameKey: 'metric.ck',
    aliases: ['CK', 'CPK', 'Kreatinkináza', 'Creatine kinase', 'Kreatinfosfokináza', 'S-CK'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0, high: 1000 },
  },
  {
    key: 'cholinesterase',
    nameKey: 'metric.cholinesterase',
    aliases: ['CHE', 'Cholinesteráza', 'Cholinesterase', 'Pseudocholinesteráza', 'S-CHE'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ukat/L',
    units: ['ukat/L', 'U/L'],
    precision: { 'ukat/L': 2, 'U/L': 0 },
    typicalRange: { low: 0, high: 500 },
  },

  // Substrates (serum)
  {
    key: 'phosphate',
    nameKey: 'metric.phosphate',
    aliases: [
      'Phosphate',
      'Fosfor',
      'Fosfor anorganický',
      'Fosfát',
      'Anorganický fosfát',
      'P',
      'S-Fosfor',
      'Phosphorus',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/L',
    units: ['mmol/L', 'mg/dL'],
    // Reported as elemental phosphorus (30.97 g/mol) — bridges mmol/L <-> mg/dL.
    molarMass: 30.97,
    precision: { 'mmol/L': 2, 'mg/dL': 1 },
    typicalRange: { low: 0.1, high: 10 },
    preferredUnitByLocale: { cs: 'mmol/L', en: 'mg/dL' },
  },
  {
    key: 'osmolality',
    nameKey: 'metric.osmolality',
    aliases: ['Osmolality', 'Osmolalita', 'Osmolalita séra', 'S-Osmolalita', 'Osmol'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mmol/kg',
    units: ['mmol/kg'],
    precision: { 'mmol/kg': 0 },
    typicalRange: { low: 100, high: 500 },
  },
  {
    key: 'homocysteine',
    nameKey: 'metric.homocysteine',
    aliases: ['Homocysteine', 'Homocystein', 'HCY', 'S-Homocystein'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L'],
    precision: { 'umol/L': 1 },
    typicalRange: { low: 0, high: 500 },
  },
  {
    key: 'bilirubin-direct',
    nameKey: 'metric.bilirubin-direct',
    aliases: [
      'Direct bilirubin',
      'Conjugated bilirubin',
      'Bilirubin přímý',
      'Bilirubin konjugovaný',
      'Přímý bilirubin',
      'Konjugovaný bilirubin',
      'S-Bilirubin přímý',
      'DBIL',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L', 'mg/dL'],
    molarMass: 584.66,
    precision: { 'umol/L': 1, 'mg/dL': 2 },
    typicalRange: { low: 0, high: 600 },
    preferredUnitByLocale: { cs: 'umol/L', en: 'mg/dL' },
  },

  // Iron panel completion
  {
    key: 'transferrin',
    nameKey: 'metric.transferrin',
    aliases: ['Transferrin', 'Transferin', 'TRF', 'S-Transferin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L'],
    precision: { 'g/L': 2 },
    typicalRange: { low: 0.1, high: 10 },
  },
  {
    key: 'tibc',
    nameKey: 'metric.tibc',
    aliases: [
      'TIBC',
      'Celková vazebná kapacita železa',
      'Celková vazebná kapacita',
      'Total iron binding capacity',
      'Vazebná kapacita železa',
      'CVK',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L'],
    precision: { 'umol/L': 0 },
    typicalRange: { low: 5, high: 200 },
  },
  {
    key: 'transferrin-saturation',
    nameKey: 'metric.transferrin-saturation',
    aliases: [
      'Transferrin saturation',
      'Saturace transferinu',
      'Sytnost transferinu',
      'TSAT',
      'SAT-TRF',
      'Saturace transferrinu železem',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 0 },
    typicalRange: { low: 0, high: 100 },
  },

  // Thyroid panel completion
  {
    key: 'ft3',
    nameKey: 'metric.ft3',
    aliases: ['fT3', 'FT3', 'Free T3', 'Free triiodothyronine', 'Volný trijodtyronin', 'T3 volný'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'pmol/L',
    units: ['pmol/L'],
    precision: { 'pmol/L': 1 },
    typicalRange: { low: 0.5, high: 60 },
  },

  // Inflammation / immunity
  {
    key: 'aslo',
    nameKey: 'metric.aslo',
    aliases: ['ASLO', 'ASO', 'Antistreptolyzin O', 'Antistreptolysin O', 'Anti-streptolysin O'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/mL',
    units: ['[IU]/mL'],
    precision: { '[IU]/mL': 0 },
    typicalRange: { low: 0, high: 5000 },
  },
  {
    key: 'rheumatoid-factor',
    nameKey: 'metric.rheumatoid-factor',
    aliases: ['RF', 'Revmatoidní faktor', 'Rheumatoid factor', 'Revmatoidní faktor (RF)'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/mL',
    units: ['[IU]/mL'],
    precision: { '[IU]/mL': 0 },
    typicalRange: { low: 0, high: 5000 },
  },

  // Haematology completion — reticulocytes, ESR, 5-part differential (relative)
  {
    key: 'reticulocytes',
    nameKey: 'metric.reticulocytes',
    aliases: ['Reticulocytes', 'Retikulocyty', 'Reti', 'RET', 'Retikulocyty absolutně'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '10*9/L',
    units: ['10*9/L'],
    precision: { '10*9/L': 0 },
    typicalRange: { low: 0, high: 1000 },
  },
  {
    key: 'esr',
    nameKey: 'metric.esr',
    aliases: [
      'ESR',
      'FW',
      'Sedimentace',
      'Sedimentace erytrocytů',
      'Rychlost sedimentace erytrocytů',
      'Erythrocyte sedimentation rate',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mm/h',
    units: ['mm/h'],
    precision: { 'mm/h': 0 },
    typicalRange: { low: 0, high: 200 },
  },
  {
    key: 'neutrophils',
    nameKey: 'metric.neutrophils',
    aliases: [
      'Neutrophils',
      'Neutrofily',
      'Segmenty',
      'Neutrofilní granulocyty',
      'NEUT',
      'Neutrofily %',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 1 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'lymphocytes',
    nameKey: 'metric.lymphocytes',
    aliases: ['Lymphocytes', 'Lymfocyty', 'LYMPH', 'Ly', 'Lymfocyty %'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 1 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'monocytes',
    nameKey: 'metric.monocytes',
    aliases: ['Monocytes', 'Monocyty', 'MONO', 'Mo', 'Monocyty %'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 1 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'eosinophils',
    nameKey: 'metric.eosinophils',
    aliases: ['Eosinophils', 'Eozinofily', 'EO', 'Eosinofily', 'Eozinofily %'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 1 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'basophils',
    nameKey: 'metric.basophils',
    aliases: ['Basophils', 'Bazofily', 'BASO', 'Ba', 'Bazofily %'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 1 },
    typicalRange: { low: 0, high: 100 },
  },

  // Urine sediment (quantitative counts) — SmartMedix gaps, distinct from the
  // qualitative dipstick metrics urine-blood / urine-leukocyte-esterase.
  {
    key: 'urine-erythrocytes',
    nameKey: 'metric.urine-erythrocytes',
    aliases: [
      'Erytrocyty v moči',
      'Erytrocyty (sediment)',
      'Sediment - erytrocyty',
      'Erytrocyty močový sediment',
      'U-Erytrocyty',
      'Urine erythrocytes',
      'Erytrocyty v moči (počet)',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '/uL',
    units: ['/uL'],
    precision: { '/uL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'urine-leukocytes',
    nameKey: 'metric.urine-leukocytes',
    aliases: [
      'Leukocyty v moči - sediment',
      'Leukocyty (sediment)',
      'Sediment - leukocyty',
      'Leukocyty močový sediment',
      'U-Leukocyty sediment',
      'Urine sediment leukocytes',
      'Leukocyty v moči (počet)',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '/uL',
    units: ['/uL'],
    precision: { '/uL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },

  // --- Category-pack analytes (compiled from the former pack "extras") --------
  // These complete the clinical categories the routine core deliberately omits
  // (see docs/ANALYZA-SEED-PACKY.md). They are built-in so an import ALWAYS
  // resolves them even when their category pack is inactive; their VISIBILITY is
  // gated by the owning pack (see core/packs.ts). No LOINC is shipped for them
  // (the source corpus carries none; codes are never invented).

  // Kidney (also biochemistry): cystatin C completes the renal-function picture.
  {
    key: 'cystatin-c',
    nameKey: 'metric.cystatin-c',
    aliases: ['Cystatin C', 'Cystatin', 'S-Cystatin C', 'Cystatin C v séru'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mg/L',
    units: ['mg/L'],
    precision: { 'mg/L': 2 },
    typicalRange: { low: 0.1, high: 10 },
  },

  // Thyroid: the two routine thyroid autoantibodies.
  {
    key: 'anti-tpo',
    nameKey: 'metric.anti-tpo',
    aliases: [
      'Anti-TPO',
      'aTPO',
      'ATPO',
      'Protilátky proti tyreoidální peroxidáze',
      'Anti-thyroperoxidase',
      'TPO antibodies',
      'Protilátky anti-TPO',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/mL',
    units: ['[IU]/mL'],
    precision: { '[IU]/mL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'anti-tg',
    nameKey: 'metric.anti-tg',
    aliases: [
      'Anti-Tg',
      'aTG',
      'ATG',
      'Protilátky proti tyreoglobulinu',
      'Anti-thyroglobulin',
      'Thyroglobulin antibodies',
      'Protilátky anti-TG',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/mL',
    units: ['[IU]/mL'],
    precision: { '[IU]/mL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },

  // Diabetes: insulin (fasting / IRI).
  {
    key: 'insulin',
    nameKey: 'metric.insulin',
    aliases: ['Insulin', 'Inzulín', 'Inzulin', 'S-Inzulín', 'IRI', 'Immunoreactive insulin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'm[IU]/L',
    units: ['m[IU]/L'],
    precision: { 'm[IU]/L': 1 },
    typicalRange: { low: 0, high: 1000 },
  },

  // Endocrinology / hormones: the routine reproductive + adrenal panel.
  {
    key: 'fsh',
    nameKey: 'metric.fsh',
    aliases: ['FSH', 'Folikulostimulační hormon', 'Follicle stimulating hormone', 'Folitropin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/L',
    units: ['[IU]/L'],
    precision: { '[IU]/L': 1 },
    typicalRange: { low: 0, high: 300 },
  },
  {
    key: 'lh',
    nameKey: 'metric.lh',
    aliases: ['LH', 'Luteinizační hormon', 'Luteinizing hormone', 'Lutropin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/L',
    units: ['[IU]/L'],
    precision: { '[IU]/L': 1 },
    typicalRange: { low: 0, high: 300 },
  },
  {
    key: 'estradiol',
    nameKey: 'metric.estradiol',
    aliases: ['Estradiol', 'E2', 'Oestradiol', '17-beta-estradiol'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'pmol/L',
    units: ['pmol/L'],
    precision: { 'pmol/L': 0 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'testosterone',
    nameKey: 'metric.testosterone',
    aliases: ['Testosteron', 'Testosterone', 'Total testosterone', 'Celkový testosteron'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L'],
    precision: { 'nmol/L': 2 },
    typicalRange: { low: 0, high: 200 },
  },
  {
    key: 'prolactin',
    nameKey: 'metric.prolactin',
    aliases: ['Prolaktin', 'Prolactin', 'PRL'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'm[IU]/L',
    units: ['m[IU]/L'],
    precision: { 'm[IU]/L': 0 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'cortisol',
    nameKey: 'metric.cortisol',
    aliases: ['Kortizol', 'Cortisol', 'Ranní kortizol', 'Kortizol ranní'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L'],
    precision: { 'nmol/L': 0 },
    typicalRange: { low: 0, high: 5000 },
  },
  {
    key: 'progesterone',
    nameKey: 'metric.progesterone',
    aliases: ['Progesteron', 'Progesterone'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L'],
    precision: { 'nmol/L': 2 },
    typicalRange: { low: 0, high: 2000 },
  },
  {
    key: 'shbg',
    nameKey: 'metric.shbg',
    aliases: ['SHBG', 'Sex hormone binding globulin', 'Globulin vázající pohlavní hormony'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'nmol/L',
    units: ['nmol/L'],
    precision: { 'nmol/L': 1 },
    typicalRange: { low: 0, high: 500 },
  },
  {
    key: 'dheas',
    nameKey: 'metric.dheas',
    aliases: ['DHEA-S', 'DHEAS', 'Dehydroepiandrosteron sulfát', 'Dehydroepiandrosterone sulfate'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'umol/L',
    units: ['umol/L'],
    precision: { 'umol/L': 2 },
    typicalRange: { low: 0, high: 100 },
  },
  // Parathormon is BOTH an endocrine hormone and a bone-turnover marker, so it
  // carries both category tags and belongs to the hormones and bone packs.
  {
    key: 'pth',
    nameKey: 'metric.pth',
    aliases: ['PTH', 'Parathormon', 'iPTH', 'Parathyroid hormone', 'Parathormon intaktní'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'pmol/L',
    units: ['pmol/L'],
    precision: { 'pmol/L': 1 },
    typicalRange: { low: 0, high: 200 },
  },

  // Tumour markers: the routine serum markers beyond the core PSA panel + FOB.
  {
    key: 'cea',
    nameKey: 'metric.cea',
    aliases: ['CEA', 'Karcinoembryonální antigen', 'Carcinoembryonic antigen'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L', 'ng/mL'],
    precision: { 'ug/L': 1, 'ng/mL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'afp',
    nameKey: 'metric.afp',
    aliases: ['AFP', 'Alfa-fetoprotein', 'Alpha-fetoprotein', 'Alfa 1 fetoprotein'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L', 'ng/mL'],
    precision: { 'ug/L': 1, 'ng/mL': 1 },
    typicalRange: { low: 0, high: 1000000 },
  },
  {
    key: 'ca-125',
    nameKey: 'metric.ca-125',
    aliases: ['CA 125', 'CA-125', 'CA125', 'Cancer antigen 125'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'U/mL',
    units: ['U/mL'],
    precision: { 'U/mL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'ca-15-3',
    nameKey: 'metric.ca-15-3',
    aliases: ['CA 15-3', 'CA-15-3', 'CA153', 'Cancer antigen 15-3'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'U/mL',
    units: ['U/mL'],
    precision: { 'U/mL': 1 },
    typicalRange: { low: 0, high: 100000 },
  },
  {
    key: 'ca-19-9',
    nameKey: 'metric.ca-19-9',
    aliases: ['CA 19-9', 'CA-19-9', 'CA199', 'Cancer antigen 19-9'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'U/mL',
    units: ['U/mL'],
    precision: { 'U/mL': 1 },
    typicalRange: { low: 0, high: 1000000 },
  },
  {
    key: 'beta-hcg',
    nameKey: 'metric.beta-hcg',
    aliases: [
      'beta-hCG',
      'β-hCG',
      'hCG',
      'Choriogonadotropin',
      'Human chorionic gonadotropin',
      'Celkový hCG',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '[IU]/L',
    units: ['[IU]/L'],
    precision: { '[IU]/L': 1 },
    typicalRange: { low: 0, high: 1000000 },
  },

  // Coagulation: the routine coagulation screen.
  {
    key: 'inr',
    nameKey: 'metric.inr',
    aliases: ['INR', 'Quick INR', 'International normalized ratio', 'Protrombinový čas INR'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '{INR}',
    units: ['{INR}'],
    precision: { '{INR}': 2 },
    typicalRange: { low: 0, high: 20 },
  },
  {
    key: 'pt-quick',
    nameKey: 'metric.pt-quick',
    aliases: [
      'Quick',
      'PT',
      'Protrombinový čas',
      'Protrombinový test',
      'Prothrombin time',
      'PT (Quick)',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 0 },
    typicalRange: { low: 0, high: 200 },
  },
  {
    key: 'aptt',
    nameKey: 'metric.aptt',
    aliases: [
      'aPTT',
      'APTT',
      'Aktivovaný parciální tromboplastinový čas',
      'Activated partial thromboplastin time',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 's',
    units: ['s'],
    precision: { s: 1 },
    typicalRange: { low: 0, high: 300 },
  },
  {
    key: 'fibrinogen',
    nameKey: 'metric.fibrinogen',
    aliases: ['Fibrinogen', 'Fibrinogen dle Clausse', 'FBG'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'g/L',
    units: ['g/L'],
    precision: { 'g/L': 2 },
    typicalRange: { low: 0, high: 20 },
  },
  {
    key: 'd-dimer',
    nameKey: 'metric.d-dimer',
    aliases: ['D-dimer', 'D-dimery', 'D dimer', 'DDI'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'mg/L',
    units: ['mg/L'],
    precision: { 'mg/L': 2 },
    typicalRange: { low: 0, high: 100 },
  },
  {
    key: 'antithrombin',
    nameKey: 'metric.antithrombin',
    aliases: ['Antitrombin III', 'Antitrombin', 'AT III', 'ATIII', 'Antithrombin'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: '%',
    units: ['%'],
    precision: { '%': 0 },
    typicalRange: { low: 0, high: 200 },
  },

  // Cardiac markers (troponin + myoglobin; NT-proBNP already lives in the core).
  {
    key: 'troponin',
    nameKey: 'metric.troponin',
    aliases: [
      'Troponin',
      'Troponin T',
      'Troponin I',
      'hs-troponin T',
      'hs-cTnT',
      'hs-cTnI',
      'Vysoce senzitivní troponin',
    ],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ng/L',
    units: ['ng/L'],
    precision: { 'ng/L': 0 },
    typicalRange: { low: 0, high: 1000000 },
  },
  {
    key: 'myoglobin',
    nameKey: 'metric.myoglobin',
    aliases: ['Myoglobin', 'MYO'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L'],
    precision: { 'ug/L': 0 },
    typicalRange: { low: 0, high: 100000 },
  },

  // Bone metabolism: the routine bone-turnover markers.
  {
    key: 'osteocalcin',
    nameKey: 'metric.osteocalcin',
    aliases: ['Osteokalcin', 'Osteocalcin', 'NMID osteokalcin', 'Osteocalcin N-MID'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L'],
    precision: { 'ug/L': 1 },
    typicalRange: { low: 0, high: 500 },
  },
  {
    key: 'beta-crosslaps',
    nameKey: 'metric.beta-crosslaps',
    aliases: ['beta-CrossLaps', 'β-CrossLaps', 'CTX', 'Beta-CrossLaps (CTX)', 'C-telopeptid'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L'],
    precision: { 'ug/L': 2 },
    typicalRange: { low: 0, high: 50 },
  },
  {
    key: 'p1np',
    nameKey: 'metric.p1np',
    aliases: ['P1NP', 'PINP', 'Prokolagen typu 1 N-propeptid', 'Total P1NP'],
    category: 'lab',
    valueType: 'number',
    canonicalUnit: 'ug/L',
    units: ['ug/L'],
    precision: { 'ug/L': 1 },
    typicalRange: { low: 0, high: 1000 },
  },
];

/**
 * Auto-seeded tags per built-in metric key (metric tags, phase 1). Each metric
 * gets a specimen tag (blood / urine / stool / vitals) and, where clearly
 * classifiable, one or more clinical panel tags. Ambiguous metrics keep only
 * their specimen tag. See `tags.ts` for the vocabulary and grouping rules.
 *
 * Rules applied here:
 *  - specimen: every `urine-*` → urine; stool (fob) → stool; the remaining lab
 *    (serum/blood) metrics → blood; home/body metrics → vitals;
 *  - panels: cbc, lipids, liver, kidney, thyroid, diabetes, vitamins, iron and
 *    tumor-markers for the metrics that clearly belong to them (a metric may
 *    carry both a specimen and a panel tag, e.g. creatinine → [blood, kidney]).
 */
const TAGS_BY_KEY: Record<string, string[]> = {
  // Lipids (blood)
  'total-cholesterol': ['blood', 'lipids'],
  'ldl-cholesterol': ['blood', 'lipids'],
  'hdl-cholesterol': ['blood', 'lipids'],
  triglycerides: ['blood', 'lipids'],
  'lipoprotein-a': ['blood', 'lipids'],
  // Glucose metabolism / diabetes (blood)
  glucose: ['blood', 'diabetes'],
  hba1c: ['blood', 'diabetes'],
  'c-peptide': ['blood', 'diabetes'],
  'anti-gad': ['blood', 'diabetes'],
  // Kidney (blood, except the urine-derived ones)
  creatinine: ['blood', 'kidney'],
  egfr: ['blood', 'kidney'],
  'uric-acid': ['blood', 'kidney'],
  urea: ['blood', 'kidney'],
  // Liver (blood)
  alt: ['blood', 'liver'],
  ast: ['blood', 'liver'],
  ggt: ['blood', 'liver'],
  alp: ['blood', 'liver'],
  'bilirubin-total': ['blood', 'liver'],
  // Thyroid (blood)
  tsh: ['blood', 'thyroid'],
  ft4: ['blood', 'thyroid'],
  // Vitamins (blood)
  'vitamin-d': ['blood', 'vitamins'],
  'vitamin-b12': ['blood', 'vitamins'],
  folate: ['blood', 'vitamins'],
  // Iron (blood)
  iron: ['blood', 'iron'],
  ferritin: ['blood', 'iron'],
  // Tumour markers
  psa: ['blood', 'tumor-markers'],
  'psa-free': ['blood', 'tumor-markers'],
  p2psa: ['blood', 'tumor-markers'],
  fob: ['stool', 'tumor-markers'],
  // Complete blood count (blood)
  hemoglobin: ['blood', 'cbc'],
  leukocytes: ['blood', 'cbc'],
  erythrocytes: ['blood', 'cbc'],
  thrombocytes: ['blood', 'cbc'],
  hematocrit: ['blood', 'cbc'],
  mcv: ['blood', 'cbc'],
  mch: ['blood', 'cbc'],
  mchc: ['blood', 'cbc'],
  rdw: ['blood', 'cbc'],
  mpv: ['blood', 'cbc'],
  // Remaining serum analytes: specimen only (no unambiguous panel)
  crp: ['blood'],
  'nt-probnp': ['blood'],
  sodium: ['blood'],
  potassium: ['blood'],
  chloride: ['blood'],
  calcium: ['blood'],
  magnesium: ['blood'],
  albumin: ['blood'],
  'total-protein': ['blood'],
  lipase: ['blood'],
  // Seed expansion — lipids
  'non-hdl-cholesterol': ['blood', 'lipids'],
  'apolipoprotein-a1': ['blood', 'lipids'],
  'apolipoprotein-b': ['blood', 'lipids'],
  // Seed expansion — biochemistry enzymes / substrates
  amylase: ['blood', 'biochemistry'],
  'amylase-pancreatic': ['blood', 'biochemistry'],
  ld: ['blood', 'biochemistry'],
  ck: ['blood', 'biochemistry'],
  cholinesterase: ['blood', 'biochemistry', 'liver'],
  phosphate: ['blood', 'biochemistry'],
  osmolality: ['blood', 'biochemistry'],
  homocysteine: ['blood', 'biochemistry'],
  'bilirubin-direct': ['blood', 'liver'],
  // Seed expansion — iron panel
  transferrin: ['blood', 'iron'],
  tibc: ['blood', 'iron'],
  'transferrin-saturation': ['blood', 'iron'],
  // Seed expansion — thyroid
  ft3: ['blood', 'thyroid'],
  // Seed expansion — inflammation / immunity (specimen only, like crp)
  aslo: ['blood'],
  'rheumatoid-factor': ['blood'],
  // Seed expansion — haematology (cbc)
  reticulocytes: ['blood', 'cbc'],
  esr: ['blood', 'cbc'],
  neutrophils: ['blood', 'cbc'],
  lymphocytes: ['blood', 'cbc'],
  monocytes: ['blood', 'cbc'],
  eosinophils: ['blood', 'cbc'],
  basophils: ['blood', 'cbc'],
  // Seed expansion — urine sediment (quantitative)
  'urine-erythrocytes': ['urine'],
  'urine-leukocytes': ['urine'],
  // Category-pack analytes (compiled from the former pack "extras").
  'cystatin-c': ['blood', 'kidney', 'biochemistry'],
  'anti-tpo': ['blood', 'thyroid'],
  'anti-tg': ['blood', 'thyroid'],
  insulin: ['blood', 'diabetes'],
  fsh: ['blood', 'hormones'],
  lh: ['blood', 'hormones'],
  estradiol: ['blood', 'hormones'],
  testosterone: ['blood', 'hormones'],
  prolactin: ['blood', 'hormones'],
  cortisol: ['blood', 'hormones'],
  progesterone: ['blood', 'hormones'],
  shbg: ['blood', 'hormones'],
  dheas: ['blood', 'hormones'],
  // Parathormon spans two categories (endocrine hormone + bone-turnover marker).
  pth: ['blood', 'hormones', 'bone'],
  cea: ['blood', 'tumor-markers'],
  afp: ['blood', 'tumor-markers'],
  'ca-125': ['blood', 'tumor-markers'],
  'ca-15-3': ['blood', 'tumor-markers'],
  'ca-19-9': ['blood', 'tumor-markers'],
  'beta-hcg': ['blood', 'tumor-markers'],
  inr: ['blood', 'coagulation'],
  'pt-quick': ['blood', 'coagulation'],
  aptt: ['blood', 'coagulation'],
  fibrinogen: ['blood', 'coagulation'],
  'd-dimer': ['blood', 'coagulation'],
  antithrombin: ['blood', 'coagulation'],
  troponin: ['blood', 'cardiac'],
  myoglobin: ['blood', 'cardiac'],
  osteocalcin: ['blood', 'bone'],
  'beta-crosslaps': ['blood', 'bone'],
  p1np: ['blood', 'bone'],
  // Urine analytes (specimen: urine)
  'urine-protein': ['urine'],
  'urine-glucose': ['urine'],
  'urine-ketones': ['urine'],
  'urine-bilirubin': ['urine'],
  'urine-urobilinogen': ['urine'],
  'urine-nitrite': ['urine'],
  'urine-blood': ['urine'],
  'urine-leukocyte-esterase': ['urine'],
  'urine-ph': ['urine'],
  'urine-albumin': ['urine', 'kidney'],
  'urine-creatinine': ['urine', 'kidney'],
  acr: ['urine', 'kidney'],
  // Home / body measurements (vitals)
  'bp-systolic': ['vitals'],
  'bp-diastolic': ['vitals'],
  'heart-rate': ['vitals'],
  'body-weight': ['vitals'],
  waist: ['vitals'],
  'body-temperature': ['vitals'],
  spo2: ['vitals'],
};

/** Built-in metrics with derived ids and auto-seeded tags. Overrides live in the user's own data. */
export const BUILTIN_METRICS: readonly Metric[] = SEED.map((m) => {
  const tags = m.key ? TAGS_BY_KEY[m.key] : undefined;
  return {
    ...m,
    id: `builtin:${m.key}` as MetricId,
    ...(tags ? { tags } : {}),
  };
});
